# Generated by Django 3.1.1 on 2020-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('CourseNumber', models.IntegerField(max_length=10)),
                ('InstructorName', models.CharField(max_length=50)),
                ('Duration', models.FloatField(max_length=20)),
            ],
        ),
    ]
