# Generated by Django 3.1.1 on 2020-09-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_beginner_expert_intermediate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='djangoclasses_ptr',
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='djangoclasses_ptr',
        ),
        migrations.DeleteModel(
            name='beginner',
        ),
        migrations.DeleteModel(
            name='expert',
        ),
        migrations.DeleteModel(
            name='intermediate',
        ),
    ]
